### ISSUE TITLE
"@"  at the beginning of the password.

### ISSUE THREAD

**Issue by BustaGraphic** [Dialosoft/backend-old#27]
**Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Register a user with "@" at the beginning of the password.
2. Try login
3. Error 401

**Expected Behavior**
Redirect to main page.

**Screenshots**

**Environment**
 - OS: [e.g. Windows, macOS, Linux]
 - Browser: [e.g. Chrome, Safari, Firefox]
 - Version: [e.g. 22]

**Additional Information**

**Comment by Flussen** [comment]
solve
